### ISSUE TITLE
Compile Error in recent cmangos pull

### ISSUE THREAD

**Issue by Talmeron** [blueboy/portal#62]
/home/exaurdon/cmangos/src/game/playerbot/PlayerbotAI.cpp: In member function ‘void PlayerbotAI::Feast()’:
/home/exaurdon/cmangos/src/game/playerbot/PlayerbotAI.cpp:2925:65: error: ‘class Player’ has no member named ‘getPowerType’
     if (!(m_bot->GetHealth() < m_bot->GetMaxHealth() || (m_bot->getPowerType() == POWER_MANA && m_bot->GetPower(POWER_MANA) < m_bot->GetMaxPower(POWER_MANA))))
                                                                 ^
/home/exaurdon/cmangos/src/game/playerbot/PlayerbotAI.cpp:2935:16: error: ‘class Player’ has no member named ‘getPowerType’
     if (m_bot->getPowerType() == POWER_MANA && CurrentTime() > m_TimeDoneDrinking
                ^
make[2]: *** [src/game/CMakeFiles/game.dir/playerbot/PlayerbotAI.cpp.o] Error 1
make[1]: *** [src/game/CMakeFiles/game.dir/all] Error 2
make: *** [all] Error 2

**Comment by cala** [comment]
Building is fixed.
