### ISSUE TITLE
Playerbot compiles but linking fails when using VC120

### ISSUE THREAD

**Issue by Yrvedon** [blueboy/portal#66]
Happens for Playerbot/tbc and Playerbot/wotlk as explained on:
http://cmangos.net/thread-6930.html
Haven't tested this on Playerbot/classic

**Comment by apo126** [comment]
I came across the same problem as described above. Compilation of only Cmangos wotlk is ok, but it has errors with playerbot.

**Comment by HerrTrigger** [comment]
See:
http://cmangos.net/thread-6942.html

**Comment by blueboy** [comment]
Sorry guys I haven't got the time these days to be involved in playerbot. I know cala is doing an excellent job with the backports. If it's O.K with cala, I have added him to the collaborators list for portal. This should allow him to push code to the wotlk repos. Hope this helps a little and all the best.

**Comment by HerrTrigger** [comment]
Thank you, cheers! :+1:

**Comment by apo126** [comment]
Blueboy, please add Cala. Thank you!

**Comment by cala** [comment]
Fixed by https://github.com/blueboy/portal/commit/6ede0566eaf094235c37e8f21e0b0a46f35e11f4
Thanks everyone (special cheers to @blueboy :wink: )
