### ISSUE TITLE
Character logs out almost immediately.

### ISSUE THREAD

**Issue by Kreegoth** [blueboy/portal#76]
Ive downloaded the portal-master for WOTLK have almost no errors on start up with UDB latest.
Ran all Sqls.

Compilation went fine.

The problem is I make a character. Whether I summon bots or not I can barely run out of the start area in Deathknell before my character is kicked to the character select screen.

There is no crash log because the server doesnt crash it just kicks my character.

Ive reran the characters sql and its a fresh character DB.

Any ideas?

Hello again Blueboy btw!

**Comment by cala** [comment]
This is a core issue that is currently invesigated. This is not related to playerbot. I'm closing the issue. Thank you.
