### ISSUE TITLE
Git pull error

### ISSUE THREAD

**Issue by HerrTrigger** [blueboy/portal#81]
Hello guys,

In trying to update, the following appears:

![capture](https://cloud.githubusercontent.com/assets/915446/11776204/9017fdb8-a245-11e5-9167-5c4bdc245974.JPG)

Guessing related to the following commit:
https://github.com/cmangos/mangos-wotlk/commit/d5758a775b9e1cac7e28acffb73463c28c8b1a29

**Comment by cala** [comment]
Should merge correctly, now.

**Comment by HerrTrigger** [comment]
Merci :)
