### ISSUE TITLE
Questionss :D

### ISSUE THREAD

**Issue by sout12** [blueboy/portal#82]
1) Are you the person who contributed to this project with just the bots? http://www.ac-web.org/forums/showthread.php?207899-Single-Player-Project-based-on-TrinityCore-%283-3-5a%29
2) Could the bots in the future do stuff their selves? Such as dungeons,bgs,arenas or raids or even like raiding a major city in a group or something
3) Anyway to make bots like hang around major cities without being teleported, or make them duel each other ?
4) How to make bots not sit their idle, i have like 300 level 1 bots i see in the /who list just not leveling and just standing their
5) Anyway for bots to have a conversation, a bit crazy but :D
I just want the bots to act more like real players, just to add more of a better player experience :+1: D
Thanks for your time :+1:

**Comment by kennumen** [comment]
duplicate question, see [answer](https://github.com/blueboy/portalclassic/issues/23)
