### ISSUE TITLE
compiling erro after I merged with the core

### ISSUE THREAD

**Issue by rikkuzhou** [blueboy/portal#83]
I compile the CMaNGOS-WotLK core successfully， no error， but after I merged with the

Playerbot(blueboy/portal) for CMaNGOS-WotLK ，there are a lot errors

错误	11	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	4923	1	game
错误	12	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	4968	1	game
错误	14	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	9861	1	game
错误	15	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	10188	1	game
错误	16	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	10395	1	game
错误	17	error C2039: “prepare”: 不是“Spell”的成员	F:\Mangos\mangos\src\game\playerbot\PlayerbotAI.cpp	10402	1	game
错误	23	error LNK2019: 无法解析的外部符号 "public: virtual __cdecl PlayerbotMgr::~PlayerbotMgr(void)" (??1PlayerbotMgr@@UEAA@XZ)，该符号在函数 "public: virtual void * __cdecl PlayerbotMgr::`vector deleting destructor'(unsigned int)" (??_EPlayerbotMgr@@UEAAPEAXI@Z) 中被引用	F:\Mangos\mangos\win\VC120\CliRunnable.obj	mangosd
错误	24	error LNK2001: 无法解析的外部符号 "public: virtual __cdecl PlayerbotMgr::~PlayerbotMgr(void)" (??1PlayerbotMgr@@UEAA@XZ)	F:\Mangos\mangos\win\VC120\RASocket.obj	mangosd
错误	25	error LNK2019: 无法解析的外部符号 "public: virtual __cdecl PlayerbotAI::~PlayerbotAI(void)" (??1PlayerbotAI@@UEAA@XZ)，该符号在函数 "public: virtual void * __cdecl PlayerbotAI::`vector deleting destructor'(unsigned int)" (??_EPlayerbotAI@@UEAAPEAXI@Z) 中被引用	F:\Mangos\mangos\win\VC120\CliRunnable.obj	mangosd
错误	26	error LNK2001: 无法解析的外部符号 "public: virtual __cdecl PlayerbotAI::~PlayerbotAI(void)" (??1PlayerbotAI@@UEAA@XZ)	F:\Mangos\mangos\win\VC120\RASocket.obj	mangosd
错误	27	error LNK2019: 无法解析的外部符号 "private: void __cdecl PlayerbotAI::_HandleCommandHelp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class Player &)" (?_HandleCommandHelp@PlayerbotAI@@AEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVPlayer@@@Z)，该符号在函数 "private: void __cdecl PlayerbotAI::_HandleCommandHelp(char const *,class Player &)" (?_HandleCommandHelp@PlayerbotAI@@AEAAXPEBDAEAVPlayer@@@Z) 中被引用	F:\Mangos\mangos\win\VC120\CliRunnable.obj	mangosd
错误	28	error LNK2001: 无法解析的外部符号 "private: void __cdecl PlayerbotAI::_HandleCommandHelp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class Player &)" (?_HandleCommandHelp@PlayerbotAI@@AEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVPlayer@@@Z)	F:\Mangos\mangos\win\VC120\RASocket.obj	mangosd
错误	29	error LNK1120: 3 个无法解析的外部命令	F:\Mangos\mangos\bin\x64_Release\mangosd.exe	mangosd
错误	31	error LNK2019: 无法解析的外部符号 "public: virtual __cdecl PlayerbotMgr::~PlayerbotMgr(void)" (??1PlayerbotMgr@@UEAA@XZ)，该符号在函数 "public: virtual void * __cdecl PlayerbotMgr::`vector deleting destructor'(unsigned int)" (??_EPlayerbotMgr@@UEAAPEAXI@Z) 中被引用	F:\Mangos\mangos\win\VC120\precompiled.obj	ScriptDev2
错误	32	error LNK2019: 无法解析的外部符号 "public: virtual __cdecl PlayerbotAI::~PlayerbotAI(void)" (??1PlayerbotAI@@UEAA@XZ)，该符号在函数 "public: virtual void * __cdecl PlayerbotAI::`vector deleting destructor'(unsigned int)" (??_EPlayerbotAI@@UEAAPEAXI@Z) 中被引用	F:\Mangos\mangos\win\VC120\precompiled.obj	ScriptDev2
错误	33	error LNK2019: 无法解析的外部符号 "private: void __cdecl PlayerbotAI::_HandleCommandHelp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class Player &)" (?_HandleCommandHelp@PlayerbotAI@@AEAAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVPlayer@@@Z)，该符号在函数 "private: void __cdecl PlayerbotAI::_HandleCommandHelp(char const *,class Player &)" (?_HandleCommandHelp@PlayerbotAI@@AEAAXPEBDAEAVPlayer@@@Z) 中被引用	F:\Mangos\mangos\win\VC120\precompiled.obj	ScriptDev2
错误	34	error LNK1120: 3 个无法解析的外部命令	F:\Mangos\mangos\bin\x64_Release\mangosscript.dll	ScriptDev2

**Comment by rikkuzhou** [comment]
I use 2013 vs update5 1.60 boost  on win7 64bits

**Comment by cala** [comment]
Fixed by https://github.com/blueboy/portal/commit/7e69d12f81f995b29a62d5fff7ba592a5321007d
